# supabase CLI config
project_id = "hivr"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"
