export const INDIAN_CITIES = [
  "Mumbai, Maharashtra",
  "Delhi, Delhi",
  "Bangalore, Karnataka",
  "Hyderabad, Telangana",
  "Ahmedabad, Gujarat",
  "Chennai, Tamil Nadu",
  "Kolkata, West Bengal",
  "Pune, Maharashtra",
  "Jaipur, Rajasthan",
  "Lucknow, Uttar Pradesh",
  "Kanpur, Uttar Pradesh",
  "Nagpur, Maharashtra",
  "Indore, Madhya Pradesh",
  "Thane, Maharashtra",
  "Bhopal, Madhya Pradesh",
  "Visakhapatnam, Andhra Pradesh",
  "Pimpri-Chinchwad, Maharashtra",
  "Patna, Bihar",
  "Vadodara, Gujarat",
  "Ghaziabad, Uttar Pradesh",
  "Ludhiana, Punjab",
  "Agra, Uttar Pradesh",
  "Nashik, Maharashtra",
  "Faridabad, Haryana",
  "Meerut, Uttar Pradesh",
  "Rajkot, Gujarat",
  "Kalyan-Dombivli, Maharashtra",
  "Vasai-Virar, Maharashtra",
  "Varanasi, Uttar Pradesh",
  "Srinagar, Jammu and Kashmir",
  "Aurangabad, Maharashtra",
  "Dhanbad, Jharkhand",
  "Amritsar, Punjab",
  "Navi Mumbai, Maharashtra",
  "Allahabad, Uttar Pradesh",
  "Ranchi, Jharkhand",
  "Howrah, West Bengal",
  "Coimbatore, Tamil Nadu",
  "Jabalpur, Madhya Pradesh",
  "Gwalior, Madhya Pradesh",
  "Vijayawada, Andhra Pradesh",
  "Jodhpur, Rajasthan",
  "Madurai, Tamil Nadu",
  "Raipur, Chhattisgarh",
  "Kota, Rajasthan",
  "Guwahati, Assam",
  "Chandigarh, Chandigarh",
  "Solapur, Maharashtra",
  "Hubli-Dharwad, Karnataka",
  "Tiruchirappalli, Tamil Nadu",
  "Bareilly, Uttar Pradesh",
  "Moradabad, Uttar Pradesh",
  "Mysore, Karnataka",
  "Tirupur, Tamil Nadu",
  "Gurgaon, Haryana",
  "Aligarh, Uttar Pradesh",
  "Jalandhar, Punjab",
  "Bhubaneswar, Odisha",
  "Salem, Tamil Nadu",
  "Warangal, Telangana",
  "Guntur, Andhra Pradesh",
  "Bhiwandi, Maharashtra",
  "Saharanpur, Uttar Pradesh",
  "Gorakhpur, Uttar Pradesh",
  "Bikaner, Rajasthan",
  "Amravati, Maharashtra",
  "Noida, Uttar Pradesh",
  "Jamshedpur, Jharkhand",
  "Bhilai, Chhattisgarh",
  "Cuttack, Odisha",
  "Firozabad, Uttar Pradesh",
  "Kochi, Kerala",
  "Nellore, Andhra Pradesh",
  "Bhavnagar, Gujarat",
  "Dehradun, Uttarakhand",
  "Durgapur, West Bengal",
  "Asansol, West Bengal",
  "Rourkela, Odisha",
  "Nanded, Maharashtra",
  "Kolhapur, Maharashtra",
  "Ajmer, Rajasthan",
  "Akola, Maharashtra",
  "Gulbarga, Karnataka",
  "Jamnagar, Gujarat",
  "Ujjain, Madhya Pradesh",
  "Loni, Uttar Pradesh",
  "Siliguri, West Bengal",
  "Jhansi, Uttar Pradesh",
  "Ulhasnagar, Maharashtra",
  "Jammu, Jammu and Kashmir",
  "Sangli-Miraj, Maharashtra",
  "Mangalore, Karnataka",
  "Erode, Tamil Nadu",
  "Belgaum, Karnataka",
  "Kurnool, Andhra Pradesh",
  "Ambattur, Tamil Nadu",
  "Rajahmundry, Andhra Pradesh",
  "Malegaon, Maharashtra",
  "Udaipur, Rajasthan",
  "New Delhi, Delhi",
  "Tirunelveli, Tamil Nadu",
  "Shimla, Himachal Pradesh",
  "Panaji, Goa",
  "Imphal, Manipur",
  "Shillong, Meghalaya",
  "Agartala, Tripura",
  "Aizawl, Mizoram",
  "Kohima, Nagaland",
  "Gangtok, Sikkim",
  "Itanagar, Arunachal Pradesh",
];

export const INDIAN_COLLEGES = [
  "IIT Bombay",
  "IIT Delhi",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Madras",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT Indore",
  "IIT (BHU) Varanasi",
  "IIT Dhanbad",
  "IIT Bhubaneswar",
  "IIT Gandhinagar",
  "IIT Jodhpur",
  "IIT Mandi",
  "IIT Palakkad",
  "IIT Tirupati",
  "IIT Patna",
  "IIT Ropar",
  "IIT Bhilai",
  "IIT Goa",
  "National Institute of Technology, Trichy",
  "National Institute of Technology, Surathkal",
  "National Institute of Technology, Warangal",
  "National Institute of Technology, Calicut",
  "National Institute of Technology, Rourkela",
  "National Institute of Technology, Durgapur",
  "National Institute of Technology, Kurukshetra",
  "National Institute of Technology, Silchar",
  "National Institute of Technology, Srinagar",
  "National Institute of Technology, Patna",
  "National Institute of Technology, Raipur",
  "National Institute of Technology, Agartala",
  "National Institute of Technology, Hamirpur",
  "National Institute of Technology, Jalandhar",
  "BITS Pilani",
  "BITS Pilani, Goa Campus",
  "BITS Pilani, Hyderabad Campus",
  "BIT Mesra",
  "VIT Vellore",
  "VIT Chennai",
  "SRM Institute of Science and Technology",
  "Manipal Institute of Technology",
  "Delhi Technological University",
  "NSUT Delhi",
  "IIIT Hyderabad",
  "IIIT Bangalore",
  "IIIT Delhi",
  "IIIT Allahabad",
  "Amrita Vishwa Vidyapeetham",
  "PSG College of Technology, Coimbatore",
  "Thapar Institute of Engineering and Technology",
  "Jadavpur University",
  "University of Calcutta",
  "University of Delhi",
  "University of Mumbai",
  "University of Madras",
  "Anna University",
  "Jamia Millia Islamia",
  "Aligarh Muslim University",
  "Banaras Hindu University",
  "University of Hyderabad",
  "University of Pune",
  "Panjab University",
  "Loyola College, Chennai",
  "St. Stephen's College, Delhi",
  "Christ University, Bangalore",
  "St. Xavier's College, Mumbai",
  "St. Xavier's College, Kolkata",
  "MCC, Chennai",
  "IIM Ahmedabad",
  "IIM Bangalore",
  "IIM Calcutta",
  "IIM Lucknow",
  "IIM Kozhikode",
  "IIM Indore",
  "IIM Shillong",
  "XLRI Jamshedpur",
  "FMS Delhi",
  "JBIMS Mumbai",
  "AIIMS Delhi",
  "CMC Vellore",
  "AFMC Pune",
  "Maulana Azad Medical College",
  "Grant Medical College",
  "NLSIU Bangalore",
  "NALSAR Hyderabad",
  "NUJS Kolkata",
  "Campus Law Centre, DU",
  "DA-IICT Gandhinagar",
  "Ambedkar University Delhi",
  "Tata Institute of Social Sciences",
  "Symbiosis International University",
  "Sathyabama Institute of Science and Technology",
  "Sikkim Manipal University",
];
